
= Good Economics for Hard Times 好的经济学
:toc:

---

== 正统经济学

==== 经济学不是精确的学科

经济学家不是物理学家那种意义上的科学家，他们往往无法给出绝对意义上的确定性。这意味着经济学家经常会犯错。

经济学家就像在医学领域一样，我们永远不能确定我们已经掌握了真理。我们只是对一个答案有足够的信心并将之付诸实践，并在之后根据情形变化再做调整。

---

==== 经济未来趋势, 无法预测

预测未来几乎是不可能的，因此大多数学院派经济学家对未来学都敬而远之。

原因 :

- *在现实世界中，影响经济增长的因素错综复杂，多得令人难以置信，而为了便于论述，经济学理论都是尽可能地将影响经济运行的因素压缩为少量几个.*

- 经济政策只是整个社会制度的一部分，*几乎没有任何证据表明仅靠"经济政策"单个因素本身, 就可以超越整体社会制度，单独对"经济增长"施加影响。*

- 国家与国家之间的政策, 存在着多方面的差异，因此，**为了解释经济增长的动因，我们要纳入研究的因素, 甚至比研究的国家的数量还多，且其中很多因素是我们未曾想到或无法衡量的。**因此，这些经济分析模型的价值, 在很大程度上取决于我们对自己遴选出来，并对纳入考虑范围的因素, 抱有多大的信心。

.. 国际货币基金组织（IMF）的一项工作, 是预测近期世界经济的增长率。尽管该组织拥有非常优秀的经济学家团队，但基本上他们的预测从来没有成功过。

.. 《经济学人》杂志曾经计算过国际货币基金组织2000—2014年的预测误差的平均值。从预测时间开始的两年（比如2012年预测的2014年增长率），平均预测误差为2.8个百分点。也就是说，国际货币基金组织的经济学家做出的预测，比每年随便从-2%到10%之间挑出一个数字要稍微准确一点。如果只是将连续增长假设为4%，那么两者误差程度则不相上下。

---

==== 经济的停滞和增长的原因, 经济学也不知道

不幸的是，*正如我们不知道如何实现增长一样，我们也不知道为什么一些国家陷入困境，而另一些国家却没有*，比如为什么韩国能保持增长，而墨西哥却不能。

*我们也不知道一个陷入困境的国家, 应该如何摆脱困境。*

- 回顾漫长的经济史，不难发现，真正不同寻常的时期其实是从1820年到1970年之间的这150年，而非随后的低增长时期.  +
如果戈登的预测是正确的（即我们未来的年均增幅最终只有0.8%），那么我们也无非是回到了长期以来的平均增幅（从1700年到2012年）。这不算新常态，而是漫长历史时期内的常态。究竟孰是孰非，无人能知，除了等着时间去判断之外，别无他法。

- 就国家层面而言，几乎没有任何事情是孤立存在的，很多事情是其他因素造成的结果。如果我们发现在教育水平较高的地方，经济增长更快，那也不一定是教育政策的功劳，很可能是其他政策带来的结果。

- 总会有人问，既然中国如此成功，为什么那些经济不佳的国家不去效仿呢？事实上，我们永远不清楚应该效仿中国的哪一部分经验。

---



==== 经济学对"风险"的划分 -> 可量化 / 不可量化

经济学会将风险, 区分为 :

1. 可量化的风险（比如, 发生这种情况或另一种情况的可能性为50%:50%）
2. 其余风险


---

==== 学院派经济学家

学院派经济学家, 从未花时间来解释他们那些更加微妙的结论背后, 通常极为复杂的推理过程。

原因:

- 当今的媒体, 天然地排斥这类微妙或长篇大论的解释。(即使有, 也会在实际播出时被剪辑掉)

- 要想向普通民众准确地传达观点，需要花费巨大努力，并且还会伴随各种风险，比如普通民众会认为你的观点听来非常愚蠢; 或者你小心谨慎选择的措辞被媒体操弄，让公众误解成截然不同的意思。

但经济学家, 还是应该和民众分享观点 :  +
世界充满着复杂和不确定，经济学家必须与民众分享的最宝贵的东西往往不是他们的结论，而是他们为了得出结论的过程, 和所选择的路径 -- 他们所知道的事实，他们解释这些事实的方式，他们采取的推理步骤，他们仍然不确定的其他信息。

---

==== 在哪里可以听到理性的声音呢？ -> National Academies Press

可以阅读（免费的）美国国家科学院 National Academies Press（该机构称得上是美国最受尊敬的学术机构）编撰的报告.

美国国家科学院会不时召集专家小组，就一个问题进行讨论并得出科学的共识。

---

== 私企中的利益代言人 : 首席经济学家

这些电视经济学家, 更加愿意发表意见和预测. 但事实上他们的预测工作做得很糟糕.

---

== ---------- ----------

---

== GDP

经济增长是由劳动生产率（即每小时产出）的快速增长推动的。

---


==== GDP 无法衡量幸福感

- 当一棵树被砍倒时，GDP计算的是使用的劳动力和生产的木材，但没有扣除失去的树荫和美景。GDP只对那些能被定价和销售的东西进行评估。

- 归根结底，*GDP只是一种手段，而非目的。* 生活质量不仅仅意味着消费, 大多数人关心的是价值感和被尊重, 父母的健康，孩子的教育。 *更高的GDP或许是向穷人提供这种帮助的一种方式，但这只是其中一种方式，而且没人觉得这种方式总是最好的。*

因此, 政策重点, 需要关注具体政策所造成的直接后果，无论是在教育、技能、创业还是健康方面. 并弄明白如何有效地解决这些问题。

---

==== 如何衡量"幸福"的价值?

可以用"机会成本"理论, 来试着估计人们愿意为花在"幸福"上的时间(人们本可以用这部分时间去工作和赚钱), 付出多少钱。比如，通过观察人们浏览互联网的时间, 来衡量互联网对他们的价值。

---

== 全要素生产率（total factor productivity，TFP）

*全要素生产率的增长, 是在我们考虑了所有可衡量因素之后, 剩下的那部分因素。它们无法用经济学家能够衡量的要素变化来解释。其在一定程度上反映了科技的进步.* 比如, 在生产方法上的创新（比如链式生产或精益生产），以及创造一个良好的拖拉机租赁市场，都有助于提高全要素生产率。


---

== 错配

==== 资源错配


---

==== 工作预期错配

很多不工作的人, 在参加“竞争性考试”（目的是获得一份政府工作或在准政府组织中工作，比如属于公共部门的银行），要么在攻读学士学位，以便申请一份政府工作。**但政府工作岗位的增加速度逐渐放缓，而受过教育的人口数量却不断增加. 这导致大多数年轻人在等待他们或许永远都得不到的工作。**这就是"预期错配".

限制人们的申请次数, 或者实行更加严格的年龄限制。这样可以避免浪费大家盲目等待的时间。






---

== 资本投入 => 边际生产率 & 资本收益递减

- 资本稀缺的经济体, 增长更快，因为此时资本的"边际生产率"比较高。这意味着, 一个经济体在经过了快速增长阶段之后，就会回归平衡增长的轨道，增长可能会放缓。(“资本收益递减”).

- 在80年代的泡沫经济中，太多的优质资金追逐了太少的优质项目，结果导致银行出现了大量不良贷款(投资打了水漂).

---

== 劳动力供给

当前有效劳动力的增速受制于两个因素，一是之前的生育率，二是人们的工作意愿。

在索洛看来，这两个因素似乎在更大程度上受到"人口学"因素的驱动，而非"经济学"因素的驱动，这就是为什么将劳动力的增长率称为“自然增长率”的原因.

---

== ---------- ----------


---

== 贸易自由化, 底层失业, 导致贫富差距加大

---

== 自动化技术, 取代原始工作岗位, 导致贫富差距加大

---


== ---------- ----------


---

== 如何提高普通公民的生活质量

- 尽管好几代经济学家付出了最大努力，*但经济持续增长的内在机制仍然难以捉摸。谁都不知道富裕国家的经济增长, 是否会再次提速，也没人知道如何才能提高实现这种事情的可能性。* 所以, 我们更有意义的研究重心, 不是"如何让国家变得更富有"，而是应放在"如何提高普通公民的生活质量"上。

- *总是期待市场创造公正的、可接受的甚至高效的结果, 是不合理的。* 一定程度的政府干预是有必要的. 更普遍地讲，在一个不平等程度急剧上升、赢者通吃的世界里，穷人和富人的生活正在产生巨大差异， *如果我们把所有社会问题甩给市场，这种差异将无法逆转。*

- 当这些年来贸易一边抢走人们的生计，一边却宣称让每个人过得更好时，政府一直在袖手旁观。如果我们想让贸易给所有人带来好处，就要设计一套好的制度。*这套制度应该包括如何鉴定经济上的失败者，以及如何为他们提供补偿。*

- 聚焦一些定义明确的干预措施的一大好处是，政策因此而具有了可衡量的目标，因此可以直接评估。我们可以拿这些政策来做实验，放弃那些没用的政策，并强化那些潜力大的。

---

==== 不能用"推动经济增长"的民意, 来做出"损害穷人"的政策

所谓的“为了维持增长态势, 而采取对商业友好政策”, 其实是为各种有利于富人、不利于穷人的政策, 打开了一扇方便之门（比如动用纳税人的钱, 去救助负债累累的公司和富人）, 只会造成进一步的贫富差距.

---

==== 转移支付

任何重大的公共政策都需要更多的资金。即使美国对富人提高税率，达到与丹麦看齐的水平，美国总税收在GDP中的占比(2017年美国的总税收（把各级政府都考虑进去）仅占GDP的27%), 仍将远低于2017年的丹麦（46%）、法国（46%）、比利时（45%）、瑞典（44%）和芬兰（43%）。因此还需要通过征税来筹措资金.

似乎任何解决方案都应该提供两种方式 :

1. 要么帮助失败者搬家或换工作, 以限制失败者的数量，
2. 要么找到一种更好的补偿方式。



---

==== TAA（贸易调整援助计划）

- 内容 +
.. TAA为工人支付培训费用（每年高达1万美元）
.. 领取最多3年的失业救济金
.. 还会得到经济上的资助来搬家、找工作，或是购买医疗保险.

- 效果: +
总体来看，在接下来的10年里，接受再培训的工人, 比未接受培训的工人要多挣5万美元。 +
经过再培训的工人和未经培训的工人的工资水平, 想要回到同一水平线, 则需要10年的时间。

- 现状
.. 在为数不多的已经划拨给受贸易影响的县的"转移支付"当中，TAA所占的比例微乎其微。
.. 原因 :
. 资金严重不足。
. 美国政界人士, 对于向特定行业提供补贴, 持谨慎态度（因为其他行业可能会感到被忽视，并向政府游说也给自己提供保护）。

---

==== 失业培训, 帮助转型

- 许多欧洲国家在帮助人们工作转型方面的投入, 远远超过美国。丹麦在积极的劳动力市场政策（培训、就业援助等）上面的花费占GDP的2%，这使得丹麦的工作流动性较高（从一份工作直接转换到另一份工作很容易），就业与失业之间的转换也比较频繁。 +
丹麦非自愿失业的人员比例与其他经合组织成员国相似，但失业者重新找到工作的速度却快得多：丹麦3/4的失业工人在一年内重新找到了新工作。 +
重要的是，丹麦模式挺过了2008年的危机和衰退，当时的非自愿失业人数没有大幅增加。

- 而在美国，相应的数字仅为0.11%。




---

==== 全民基本收入”计划（UBI）

- 内容 : +
该计划设想, 政府不管每个人的需求如何，都派发一笔可观的基本收入保障（美国曾经提出每月给每个公民派发1000美元）。如果他们真的失业了，那么他们就算一辈子不工作，也能每个月固定领钱。

- 根据美国人口普查局的最新调查，2019年的美国贫困线标准为单身收入低于11880美元，四口之家低于25750美元。

- 该计划被反对理由 :
. 缺钱.
.. 每个月向每个美国人支付1000美元，每年将耗费3.9万亿美元，这比当前美国所有福利计划的总成本还要多出1.3万亿美元，大致相当于整个联邦预算或美国GDP总量的20%.
..  要在不削弱国防、公共教育等传统政府职能的前提下，为这样一个福利计划融资，就需要取消当前所有的福利计划，而且美国的税率也要提高到丹麦的水平。
. 随着美国人的收入逐渐提高，该计划无条件转移支付的福利金会显得越来越小，甚至对于超出某个收入水平的人而言，这个金额无异于零。
. 如果只是给比较贫穷的那一半美国人口无条件发钱，1.95万亿美元的总成本更容易负担得起，但这样一来，这种计划就有了明显的针对性.

- 现状 : +
.. 目前还没有关于该计划的长期影响的数据。我们无法确定永久的基本收入保障, 会导致受益者做出什么样的反应。
.. 不过, 根据已经实施的其他类似援助计划来看, 没有数据证明穷人会把政府救济金浪费到满足不切实际的欲望上，而非用于现实需求。

---

==== 保护被救助者的尊严

- 很多救助政策走向失败的一个原因，是没有考虑到穷人的尊严。

- 被认定为穷人是一件有损名誉的事情，这种刻板观念妨碍了符合条件的穷人去申请福利计划。

- 人们不愿意让别人给自己贴上“领取食品券”的标签，因此, 今天的各种福利券采用"电子津贴转账卡"的形式，可以像借记卡一样在结账台刷卡，避免了递交各种券带来的尴尬，或者说羞辱感。

- 如果某些工作, 明显让人们看出来是政府为了增加就业而创造出来的，那么这些工作并不会提高人们的自尊感。

- 受教育程度更高、*收入水平更高的人，往往将工作视为自我身份认同的一部分；在年收入3万美元或更少的人里面，只有37%的人表示从工作中获得了认同感。* 各个行业之间也存在显著差异。比如，*在医疗保健行业工作的人有62%表示自己从工作中获得了认同感，这个数字在教育行业是70%，在酒店业是42%，在零售或批发行业是36%。*

- **社会政策的目标, 是帮助人们吸收那些影响到自己的冲击波，而不让这些冲击波影响自我意识。**不幸的是，我们的社会保障仍有维多利亚时代的色彩，太多的政客毫不掩饰自己对穷人和弱势群体的轻视。


---


==== 降低"补助申请"的门槛

- 申请程序的规则太复杂，就会降低申请人数.

- 一些不确定自己是否能够满足申请条件的人, 似乎会主动把自己排除在申请之外(不会去申请). 因此，“无条件"现金转移支付计划, 比“有条件"现金转移支付计划更好.

---


==== 学前教育

- 良好的学前教育, 和针对贫困儿童的强化辅导, 对于提高他们的学业成绩, 效果最好。*一些孩子如果落后于年级平均水平的话，之后完全失去方向的可能性就比较大。要有效阻止这种局面，一种好办法就是让他们在学前班阶段就为进入小学做好准备，及时发现他们与别人的成绩差距，在这种差距变得太大之前就帮助他们解决在学习过程中遇到的困难。*

- 高质量的学前教育干预措施, 在短期和长期内都能产生巨大影响.

- 有证据表明，在校学习成绩的差异, 会转化为长远机遇的差异。比如，在田纳西州开展的一项随机对照实验, 将班级规模从20-25人减少到12-17人，这在短期内提高了学生的考试分数，增加了他们以后上大学的机会。

- 通过住房拥有率、储蓄状况、婚姻状况和所住社区来衡量，发现**被分配到小班的学生, 以后的生活更好。**

- 教育研究表明，**孩子们很快就理解和记住了自己在社会等级体系中的地位，而老师又强化了这种地位。**老师们被告知，有些孩子比其他人更聪明（但这些孩子们只是被随机挑选的，并不具有代表性），对待他们的方式便有所不同。

- 对于生活在贫困社区的青少年来说，暴力可能是一种常态，因此，为了避免给人留下弱者的印象，好斗甚至打架可能是必要的。“成为一个男人”计划, 就是帮助他们识别, 暴力何时算适当的反应，何时算不当反应。

---

==== 解决女性的育儿成本

- 托儿服务不足, 是美国已婚女性和低收入单身母亲面临的最严重不利条件之一。
.. 缺乏高质量的全日托儿补贴意味着，她们要么不工作（因为托儿的费用几乎和她们的收入一样高），要么不得不找一份离家近的工作（尤其是离母亲近的地方），以便于让母亲帮忙照顾孩子, 这导致她们可求职公司范围缩窄。
.. 初为人母的女性换工作, 主要原因是为了加入“对家庭友好”的公司。

- 女性会因为生养孩子而付出巨大代价，这是造成男女收入差距的很大一部分原因。
.. 男女在生孩子之前的收入几乎没有差别，而从长远来看，孩子的出生造成了男女之间大约20%的收入差距。
.. 在第一个孩子出生后，女性的职业等级和成为管理者的可能性开始落后于男性。
.. 第一个孩子出生后，也有大约13%的女性永久退出了职场。

---


==== 向机会迁居（Moving to Opportunity）

- 帮助那些最贫困地区的工人迁居别处。迁居之后，他们的收入可能是之前的两倍。

- 生活在低流动性地区的孩子, 上大学的可能性更小，而且更有可能早早地生了自己的孩子(成为单身母亲)。

---

==== 不污名化政府官僚

将官僚和政客们描绘成笨拙的白痴或腐败的无赖，是极具破坏性的。

- 原因 :

. 它引发了一种下意识的反应，即使在政府部门明显需要扩张的时候，相关提议依旧招致反对.
. 政府名声越来越不佳，就越容易导致人才不愿意加入政府。这会变成一个恶性循环.
. 厌倦政府的公民可能对当选领导人无耻腐败的消息不再感兴趣，反而会助长政府的腐败。
. 要证明政府不行，人们需要证明存在另一种替代方案来更好地实施同样的活动。

---

==== 打击腐败

目前打击腐败的方式是提高透明度，即政府的工作应该接受外部人士的监督，比如独立的公共审计机构、媒体和公众。

- 打击政府腐败绝非没有代价 :
.. 一个名为Consip的组织, 代表政府部门采购物资。但这个平台采购的产品往往要耗费更多的政府资金，即使市场上存在更便宜的替代品。各部门本来可以按照更便宜的价格购买自己需要的东西，但只要可以通过Consip组织采购，他们就决定不行使这一选择权。因为他们知道, 这样可以让自己免受腐败指控。
.. 美国的医生建议病人接受过多的检查, 以避免医疗事故诉讼。
.. 没有一家大型科技公司, 愿意竞标为奥巴马医改建立配套设施的计算机系统。原因是，政府合同条条框框太多(合同就有1000多页)。
.. 透明度监督工作往往依赖于外部人员，而这些人员理解大局的能力有限，他们能做的最多就是核实是否遵循了正当程序。这意味着官僚们往往会耗费大量精力去思考怎样做才算"正确"，才能避免引起关注和避免麻烦。这会催生一种特别注重遵循条条框框的刻板倾向(死板的官僚主义做法).

---

==== 私有化并不是灵丹妙药

私人征税（即“包税制”）的历史告诉我们，鼓励代理人去征税（或收取罚款）, 有可能会敲诈那些原本不需要缴税的.

包税制（tx frming）: 指国家将政府的征税活动, 承包给出价最高的投标者，后者只需要事前付给国家某个定额的租金, 就可以保留多余的税收收入。

---





















































