
= 认识与价值观(吴军)
:toc:


---



==== 和人相处的技巧 : 让对方感觉对你有所需求

- 世界上所有的人都喜欢自己来买东西，而不是被人推销来买东西，因此那种求人的营销一定无法成功。
.. 我经常看到一个男生为了追求一个女生，绞尽脑汁、极尽努力地去讨好对方、迁就对方，对方就是爱搭不理。这对被追求的女生而言，其实就是一种被强制推销的感觉。

- 如何避免损友，简单地讲就是不要给损友第二次机会，永远不要来往。他可能以后会变好，但是你可交往的人很多，而你的时间和精力只能维持少数的几十个。为了不在上面反复试错, 这种笨办法能够避免在朋友关系的投资上出现填不满的无底洞。

- 我们在工作中有时会见到这样一些现象，比如，领导交代某个人去和客户联系一下，约定一个时间见面。接下来的几天，如果领导不去问他，他也不会告诉领导任何结果。这个接受任务的人就有问题，*既然接受了任务，并非按照要求采取行动了就算完事了，而是需要达到目的。电话没打通，邮件没有回，就要主动想别的办法.*

- 如果做事仅仅有苦劳和辛劳的话，不仅我们的上级不会满意，周围的人也不会觉得靠谱。我有一次委托合作单位的人帮我订火车票，经办人订票时把我的证件号搞错了，也没有确认能不能拿出来。等我到了取票窗口，这张票取不出来，经办人一再向我道歉。对于这种只有苦劳的人，只能让人哭笑不得，但我通常不会再让他们第二次办事。

- 由于基因的局限性，我们很难同时交往超过 150 个人。150 个人是你一生中在亲友方面能够投资的总额，而亲戚们可能又占掉了其中的一半，剩下来能够交往的朋友或者合作伙伴就很有限了。成功的人其实在很大程度上是靠找到了志同道合的、对他帮助最大的人来帮助他.

---

==== 对人的本性只能因势利导

- "*故善者因之，其次利道之，其次教诲之，其次整齐之，最下者与之争*。"  +
成语“因势利导”就是从这段文字中发展来的。
+
太史公开篇讲了人喜欢物质享受和精神享受的天性。他说，自从舜帝和大禹的夏朝之后，*人就开始喜欢好听的音乐和美色，喜欢美食，喜欢享受，喜欢炫耀，这种习惯已经很久了，无法改变它。因此，好的统治者就随国民去了，差一点的（统治者）动之以利引导他们，再差一点的试图教化他们，更差的约束管理他们，最差的要和他们作对。*
+
既然喜欢外表(好美人)是人的本能，就不要强行改变它，只能因势利导.

.. 世界上没有什么老实的和不老实的男生之分，只有对你好和对你不好的人.  相反，通常让大家大跌眼镜、出轨离婚的，大多数是被公认为“老实”的丈夫们。包括一些在大家想象当中应该是行为楷模的人，比如中青年学者、有头有脸的公众人物，暗地里却都流露出对年轻漂亮女性的爱慕表情，甚至一些人还利用自己的光环与身份和一些漂亮的女性维持一种暧昧关系，只是这些事情通常外人并不知道罢了。

- 今天，上至很多政府领导，中到公司老板，反而不懂这个道理。他们幻想着既要马儿跑，又要马儿不吃草的社会，这种做法非常有悖于人性。

---

==== 社会活动时的体面

- 他们从小要学习如何参加社会活动，学习贵族礼仪。但是，贵族在举止上最重要的是在自然危险面前的淡定。用中国话讲，就是“泰山崩于前而色不变”。
.. 美国军人在下雨时是不打伞的，更不会匆忙奔跑避雨，他们正确的举止是穿着雨衣在雨中列队快速行走。为什么要这样？因为一名军人在灾害面前必须沉稳。
.. 奥巴马出席户外新闻发布会，下起了雨，奥巴马随即让身边的海军陆战队士兵帮忙撑伞挡雨，结果招来批评。重要的原因在于作为总统, 这种行为有失体统,  缺了点贵族气概。

---

==== 幸福感

学者们认为，幸福感的本源只有两个一一基因的传承和影响力。

[cols="1,5a"]
|===
|Header 1 |Header 2

|基因的传承
|人和其他任何物种一样，都担负着传承基因的使命.

|影响力
|人的影响力则是由其作为的宽度、深度和长度所决定的。一条河流的水量，由它的长度、宽度和深度三个因素决定，一个人的影响力也是如此。 +
而要做到更宽，则是要和一些志同道合的人在一起, 共同做一些事情。

|婚姻
|- 传统的古典爱情故事(梁祝, 罗密欧与朱丽叶等), 正因为悲剧的爱情没有结果，才让人有无限的遐想，也让人觉得如果悲剧不发生结果一定是好的。 +
但是, *完美的爱情并不意味着完美的婚姻。一段完美的爱情，仅仅是一个好的开局，但并非完美的全过程。*

- 一个人，特别是年轻的时候，可塑性很重要。虽然我们常说喜欢一个人就要包容对方的缺点，但包容一天可以，一年可以，包容一辈子是很有难度的。*幸福的婚姻不应该是一方包容另一方一辈子。  +
在这个过程中，不仅需要双方努力，而且需要对方是一个合适的人(具有可塑性)，否则再努力也没有用*。

- 对自己好，不能看对方怎么说，而要看他怎么做。*一个男生最终能否对你好，要看他有多少创造未来的能力。*

- 看一个人是否对自己好，首先要看他的“婚姻观”，即是否认可夫妻间关系的重要性高于其他关系的重要性。中国人老爱纠结“是先救妈妈，还是先救老婆（女朋友）。我首先希望女生不要问男生这个傻问题，因为男生通常不会诚实地给出答案。我建议你仔细观察他，你会发现他对这个问题的真实想法。 +
如果他经常纠结这一类问题，或者找理由来解释为什么他家里人比你更重要，趁早对这种男生说再见，因为他将来永远有借口把你牺牲掉。


|===

- *今天科技进步的结果，应该是让更多的人能够过上优雅而从容的生活，而不是让大家变得没有时间生活*，这就是我对技术进步的期望。*幸福生活才是根本，其他都不过是达成这个目的的手段而已。*

- *人一出生，死期已定. “这个世界大家其实都在排着队沿着一条路往前走，停不下来，走到尽头就是死亡。这时，有些男人和女人搭上了腔，开始说笑起来，更多的人参与了进来，整个队伍便充满了欢乐。”我想，我们的生活其实就应该是这样的。*

- *所有传世的文学作品，无论呈现的现实多严酷，都有一股借着"肯定生命"来对抗"生命无常"的基本反抗精神。*





---

== 大学的过法

==== 城市>大学>专业

高考专业的选择, 三类因素中，城市>大学>专业。当然前提是考生无法兼顾这三者时, 就按这个权重来进行抉择。

[cols="1,6a"]
|===
|Header 1 |Header 2

|城市
|- 尽量选择一线城市(北京、上海及其周边（即南京、杭州二市)，以及广州). 经济体量越大的城市，企业越集中，机会也越多，找工作面试都更方便。 +
一个公司在招人时，通常不愿意为了一所大学派一个团队专门出一趟差。也就是说，从其他城市毕业，即使你再优秀、学的专业再好，直接进入这些公司的可能性也几乎是零。
.. 深圳大学在中国排不上号，但进入腾讯、华为的人却很多。
.. 我在腾讯时，我们只到上述城市(一线城市 + 南京,杭州, 武汉、成都、西安, 哈尔滨)进行校招. 西安和哈尔滨能够入围，是大学聚集的因素，而不是经济发展的因素。 +
同样和我们竞争人才的阿里巴巴和百度，以及外企谷歌、微软、高盛等投行，麦肯锡和普华永道等咨询公司，也只到这几个城市招人。

- 随着西部大开发，尤其是“一带一路”倡议的助力，等我毕业的时候，中小城市是否会慢慢赶上来？从历史上看，这种可能性极小。

|大学
|- 美国排名前 20 位的大学都各有特色，很难讲排名第一的普林斯顿大学就比排名第十的杜克大学一定好多少。 +
但中国绝对不是这种情况，就综合水平而言，中国最好的大学有 C9(九校联盟, 联盟成员都是国家首批“985工程”重点建设的一流大学）的说法，即:  +
-> 第一档: 清华、北大、 +
-> 第二档: 复旦、上海交大、浙大、 +
-> 第三档 : 南京大学、西安交大、中科大、哈工大。 +
如果再加上我认为很好的中国人民大学、南京东南大学、天津南开大学，也就是 12 所。 +
+
每档之间, 无论是在师资、经费还是科研成果上，都是断崖式的差距。


- 刚走出校门时，*大公司通常还是按照大学的名气分配它招收员工的比例的，因为没有更好的衡量不同大学毕业生水平的方法。*
.. 世界各大投行和咨询公司, 宁可招一个北大历史系的学生，到了公司后再培养，也不愿意招其他相对差一些的大学的热门专业的学生。  +
清华企业家协会全球 400 多名会员的情况，他们最后做成的事情，其实和当初的专业几乎无关，这说明学校比专业重要。
.. 很多时候，失败不是成功之母，成功才是成功之母。成功地做过一件事情，就有可能举一反三做成第二件、第三件事情。如果从来都没有做成过一件事，以后成功的可能性就不大。 +
一个人只要成功地掌握了第一种，以后就有信心掌握第二种。一个人在年轻的时候掌握了一种技能的学习方法，在未来人生道路上就有信心适应各种变化。



|专业
|- 本科时要尽可能地选择"适应面广"的专业，以增加未来的适应能力，因为大学所学到的具体的专业知识，走出校门时有 1/3 就已经过时了，工作 5 年后又有 1/3 过时了，没有适应性就难以有未来职业的发展。
.. 数学专业的适应性比生物专业要广得多，金融专业比会计专业要广得多. 从万金油似的专业转到很专、很窄的专业有可能，反过来几乎不可能。

- **要优先考虑"高势能"的专业。所谓高势能的专业，就是指那些相对难学，而又是其他专业的基础的专业。**比如，数学专业相对计算机专业和商学就是高势能的.  +
在读研究生时, 从高势能转到低势能的专业有可能，反过来绝无可能。

- 从事数学和物理学研究，是需要极高的天赋的。*选这两个专业，打好基础后，将来是一定要转行的*。在麻省理工学院，这些专业的毕业生, 大部分是进入医学院和法学院的; 而直接参加工作的毕业生, 大部分去了华尔街，真正搞数学和物理的很少。

- 在理科中，生物和化学虽然要容易得多，但从事这两个领域的工作极为辛苦，而且不好找工作，将来很可能也需要改行。


|===

---

==== 根据自己的生活目标, 来主动培养相关技能, 而非被动地学校给什么就吃什么

[cols = "1,3a"]
|===
|Header 1 |Header 2

|以未来生活所必须的知识为学习目标
|- *大学生首先都需要明确自己未来的生活目标，主动根据这个目标尽可能地拓宽学习视野、培养技能，而不是被动接受学校的规划。* 主动性非常重要!

- 在大学应该学会什么？用一句话来讲，就是未来生活中所需要的常识、知识、技能和方法。在这里我用了“生活”而不是“职业”二字。

-  *一个人要想在走出校门时能够成为社会人，在大学就需要完成这个过程。* 当一个人走出大学校门，他就必须100%地为自己的所有行为负责。遇到的社会问题，法律问题, 不论是否有经验，都必须自己承担责任, 在大学里都需要学会。如果一个年轻人走出校门之前没有成熟到足以应付未来工作中的各种挑战，那么他今后的职业前景堪忧。

- 人的一生要经历很多阶段，不同阶段所做的事情不同. 为生活而学习的人，必须明确今后要过一个什么样的生活。 +
如果一个大学生意识到他在大学 4 年里，所需要学习的东西远不止课堂上那点内容，他恐怕就不会荒废时间去打游戏了.


|不能养成玻璃心的习惯
|- 清华大学入学时，一个年级 200 多名新生都是原来学校最顶尖的学生，但到了第一学期的期中考试，总要有最后一名，总要有最后 1/3 的学生，这时候哪些人是玻璃心马上就看出来了。

- 杜鲁门能当上副总统，主要是靠他 humble(朴实低调) 的品质，罗斯福身边并不缺聪明人，但是杜鲁门却是为数不多能够为各方所接受的人。杜鲁门和特朗普一样，都不是玻璃心的人。

|付诸行动的习惯
|- 世界上喜欢说的人多，愿意做事情的人少，不仅常人如此，很多商界领袖和政治精英也是如此。那些政客和企业家说的话有一半没有认真去落实。

- 正是因为爱说的人多、爱做的人少，恰恰给了少数实践者成功的机会。

|沟通能力和表达能力
|- 要想成为精英，这个能力一定不能少，否则就无法调动人力资源，让大家协助你实现自己的目标。
.. 在美国陆军学院（即西点军校), 和安纳波利斯美国海军学院, 每年录取的 1100~1200 名学生中，有 700 多名是参加过辩论比赛的.

|表示友善和爱的能力
|- 比友善更进一步的是爱，既包括爱情，也包括爱慕、慈爱或者欣赏。不论哪一种，人都需要懂得如何表达。如果一个人想在社会阶层上再往上跃迁几个台阶， 这个能力是必须要学会的。

- 不懂得关爱别人、不懂得分享, 没有培养关爱他人的习惯，以至他们长大以后非常小家子气。缺乏爱的人难以大气，不大气的人做不成大事。


|总结、写作和逻辑推理的能力
|- 我们的媒体上有太多缺乏逻辑的文章，包括很多社论，前提和论据完全推不出结论。

- 仅仅靠好想法本身, 未必能够说服他人，而拿出不可辩驳的事实后，任何人都难以无视事实。
.. 当时陆奇还在雅虎，要说服杨致远等人接受他对雅虎产品的新设计，*陆奇私下里做了很多功课，把杨致远等人可能问的所有问题，都事先让手底下的人做了模拟实验*。这样，他便证明了自己的方案比过去的可以给雅虎带来更多的收益。

- 说服, 还需要搬救兵. 为了宣传我们的想法，我们更需要像赫胥黎这样的人，他们不完美，甚至看法并不和我们完全一致，却能够坚持不懈地帮我们传播想法。

- 达尔文的进化论, 在很长的时间里内在的逻辑也不是非常严谨，更糟糕的是有许多和新的科学发现相矛盾的地方。所幸的是，有一大批科学家不断地用最新的科学发现修正进化论、解释进化论.

- 因此, 我们常常是需要两类同盟军的，一类是像赫胥黎那样捍卫我们思想的人，另一类是理性地帮助我们找到证据的人。一个人的成功，也要靠他调动资源的能力。聪明人总是善于借力的。

|领导力
|- 西点在录取时，对学生的品行和领导力有相当高的要求。*对于领导力的衡量，主要看高中生们在中学时所担任的社会职务和演讲比赛的结果*。 +
每一年的新生(1200 名)中，大约有 300 名过去是学生会主席, 或者全年级的班长, 另外大约 700 人是演讲队成员，占新生人数的一大半。 +
*演讲是领导力的一部分；其次，在战争中，沟通能力和表达能力非常重要。*
.. 西点军校所招收的人代表了美国对精英的要求. 它的目标是培养未来军界乃至政界的领袖。从西点军校学生的素质可以看出美国军官的素质，以及对政界精英的要求。
.. 在每年进入西点军校学习的 1200 名左右的学生中，90%是高中学校运动队队员，2/3 是运动队队长。在西点军校里，所有学生都必须参加一个运动队.


|博雅教育
|- 我非常反对大学生还没有进校，就不得不选择专业，而且选择之后还不能改变。*每一个校长都可以问一下自己，是否在 18 岁的时候就明白自己一辈子要做什么，如果答案是否定的，又怎能要求今天 18 岁的孩子做到这一点呢？*

|圈子
|- 什么样的圈子，决定了什么样的命运。一个二流大学的在校学生选择圈子很重要，不要总是选那些能够在一起吃喝玩乐却胸无大志的所谓志同道合者。

- 哈佛商学院教给大家的第一个思想精髓是学会“玩儿”，即营造你的同学圈子。通过考试发文凭，这是培养二三流人才的做法，哈佛商学院要培养的是精英，**精英和普通人的差别不完全在于知识的多少，而在于智慧和人脉。智慧需要和大师、和高水平的人在一起切磋才能获得；人脉更是需要从一个好的同学圈子获得，这样将来他们可以互相提携。**因此，来上课(与同学接触交流)是成为精英的必由之路；至于考试，反而在其次。
.. 学院里每一个学生多少都得有点儿特长，这些是面试时考查的一方面，否则无法和大家玩儿到一起去，以后最好从小培养孩子的特长，否则长大了就难以挤进那个圈子。如果在哈佛商学院不会玩儿，恐怕 2/3 的学费是白交了.
.. 在耶鲁大学，学生一半的时间都花在了课外活动中，**因为这些看似和考试无关的活动，培养了学生的各种优秀品质，比如拼搏精神、团队精神、领导能力、社交能力、表达能力、全球视野和社会责任感。**事实上，如果在哈佛和耶鲁没有学到这些内容，就失去了在那里读书的意义。
.. “玩儿”的活动多一晚上经常有晚会，周末有各种活动。参加这些活动的，不仅有学生们自己，而且有很多来自桂谷大公司里的资深人士和高管。12 个月这么玩儿下来，除非特别不合群的人，否则想不融入一些圈子都难。今天中国的长江商学院等著名商学院，也非常看重一同参与学习以外的各种活动.



- 只有在最好的大学里，才有最好的海外交换学习的机会. 更重要的是，它们有最强的同学圈子，甚至找到好伴侣的机会更大。


|===







---
