
= 认识与价值观(吴军)
:toc:

---

== 金融计算

==== 收益函数 gain function

研究"收益函数"的目的，是选择参与者的最优策略（optimal strategy），即策略集合中能使其效用最大化的策略。

---

==== 期望值最大化 (expectation maximization)

期望值最大化原理, 原本是用来寻找一个最佳函数的:

- 首先，我们要给出一个收益函数，它代表我们的利益。
- 其次，在每个时刻, 计算出能够最大化"收益的期望值"的方向，之后沿着这个方向走一小步。
- 接下来，再从新的起点出发, 重复这个过程。

这样，不论从何处开始，最后一定能够达到收益最大的那个终点。这个过程是一个不断迭代的过程，每一步的终点都是下一步的起点，一步比一步优化。 +
这个过程也成为机器学习的基础，包括 AlphaGo。

---

== 商业价值观

==== 企业文化 = 收益函数

- 一个公司的基因, 在很大程度上取决于创始人的基因，创始人喜欢什么、树立什么样的价值观，公司最终就会演变成什么样子. +
**一个公司的创始人定下一个什么样的价值观，它就是这个公司的"收益函数"，**员工会不自觉地朝着收益最大化的方向努力。(正如同素质教育搞不过应试教育一样, 因为既然最终考核的标准就是高考, 那大家一定是往培训班上去的.)

.. 如果一个公司认定技术最重要，产品的稳定性最重要，那么久而久之，"工程师"就成了这个公司中最有权势的群体，那么工程师文化就成为公司的显性基因。谷歌就是这样的公司。
.. 如果一个公司认定技术不是最重要的，用户体验最重要，那么在这样的公司里"产品经理"就是最有拍板权势的，工程师只好围着产品经理转. 苹果、Facebook和腾讯就是这样的公司。
.. 如果一个创始人只看重销售业绩，一切以商业为先，那么这样的公司就是一个"销售导向"和"结果导向"的公司，无论是产品经理还是工程师，都要围绕着销售目标转，阿里巴巴就是这样的公司。 +
全世界只有一家公司要在每年购物季公布自己的销售业绩，这就是阿里巴巴。亚马逊和易贝（eBay）也是电商，但是从来没有做过类似的事情。
.. 如果某公司规定"销售额"是考核的标准，那么大家都会放弃对技术的长期投入、对产品细节的追求，转而考虑降低成本，采用各种方式进行促销。


- 即使是那些以销售驱动的公司，对销售业绩"收益函数"的定义也略有不同，最后得到的结果当然也完全不同。

- 一个公司"价值观"的确立, 或"企业文化"的确立，是在它成立的初期。没有一家成功的公司价值观和企业文化是在5年后确立的。


- 一切实用的设计都需要有取舍，而取舍的原则就是要围绕最终的目标。
.. 米格-25战斗机就是为了拦截美国高空高速轰炸机而设计的, 因此它整个设计方案的所有技术指标, 都是针对XB-70轰炸机，其他功能都变得次要。

.. 对于一个工程师而言，他不能等待所有条件都成熟，而是要尽可能地利用现有技术解决实际问题。 +
工程和科学不同，*好产品没有绝对正确的答案，只能在当时的情况下寻找最好的解决办法。* +
在工程上，常常是伴随着一个问题被解决，又会派生出一个新的问题。遇到问题就解决问题, 是产品经理和工程师应有的做事态度。






---

==== 在消费链条中哪一环是绕不过去的, 那一环就能挣到最大的钱!

在商业中哪里是绕不过去的一环, 那里就能挣到最大的钱，而掌握这样一环的都是平台公司.

有两种平台:

- B端 <-联系-> C端  +
如阿里巴巴. 买卖双方在平台上自动交易.  +
提供信息（或者商品）的公司或者个人，与使用（和消费）它们的人, 是严格分开的. 消费者之间也没有太多来往。

- C端 <-联系-> C端 +
像 Facebook和微信，让消费者互动起来，彼此提供信息和服务。


但是，没有人一开始就能够做出一个通用平台。能做到这个境界常常是结果，而不是一开始的目标。因为小公司一开始资源有限，只能从一个单点突破开始。

---

==== 有三种公司能够受益于"人工智能"技术


[cols="1,2a"]
|===
|Header 1 |Header 2

|1. 技术领先的大公司 (谷歌、亚马逊、微软、阿里巴巴等)
|Column 2, row 1

|2. 具有大量数据的传统公司，比如电信运营商、银行，甚至地方政府.
|- 它们商业规模非常大, 但商业模式老旧. 拥有大量数据, 却不知道如何使用.

- 它们的数据数量是一大笔财富，但是在变现之前, 它们并不等于钱. 这些公司难以依靠自己的力量从大数据中挖掘金矿。
.. 中国金融界，四大国有银行一方面看着阿里巴巴旗下的支付宝等金融产品挣大钱，另一方面则守着更多的数据干着急。如果荒废了接下来的六七年时间，它们在整个行业中落伍是确定无疑的。

- **第二类公司和第一类公司, 其实存在利益冲突, 或者潜在的利益冲突，第二类公司是不会将自己的核心业务, 委托给第一类公司的。**可以想象，四大国有银行信不过阿里巴巴，中国移动信不过腾讯；同样，花旗银行也信不过谷歌和亚马逊。反之，第一类公司也不愿意去做那些脏活、累活，因为从成本上来讲不合算。因此，第二类公司最终会暂时交给第三类公司来为自己做事。
.. 美国各大银行, 它们的策略是直接使用大数据服务公司的产品, 来处理自己的业务，而不是自己从零开始, 打造新的 IT 团队。这就给了第三类公司机会。(*但是外包给乙方的甲方核心技术, 终究会被甲方收回. 甲方现在只不过是暂时借助乙方的力量, 来帮助甲方发展起技术水平而已. 正如中国接了世界外包的活, 但最终一定会自己"产业升级"*.)

|3. 那些"愿意深入到原有产业中，了解后者产业中有什么可以通过智能技术来解决的问题，然后用新技术解决它们，从而让原有产业得到升级"的公司。
|- 由于这些都是脏活、累活，而且一开始是低利润的工作。因此大公司不愿意自己来做这件事情，这就给了小公司机会。(巨头吃肉, 小创业公司吃巨头挑剩下的渣)

- 一个案例: 华院数据研究所.  它有三类人: 工商管理硕士、数学家, 和计算机工程师。 +
-> 工商管理硕士 : 深入每一个行业和大公司了解业务逻辑，看看如何能够通过使用数据提高各行业的业务水平； +
-> 数学家: 根据具体用户的业务逻辑建立数学模型； +
-> 计算机工程师: 实现数学模型。
+
每当一个这样的小团队能够为大公司解决一些具体问题之后，华院数据就将这个小团队剥离出去，和相应的企业成立合资公司，再引入风险投资。 +
就这样，该研究所已经孵化出十多个开始挣钱的大数据公司。作为母公司华院数据本身，其实已经渐渐开始从单点突破, 往平台方向发展了.

|===


---

==== 能够逆袭大公司的小公司, 具有两个特点:

那些和大公司开展过激烈竞争，并且最后能够获胜的小公司，通常都有这样两个特点：

[cols="1,3a"]
|===
|特点 |Header 2

|1. 技术不是一个时代的
|- *同时代的其他技术进步, 能更多促进自己的技术发展, 而非更多促进别人的.* +
颠覆者（小蚂蚁）的创新, 一开始一定有很多不完善的地方, 但它必须容易得到当时相关技术的帮助，以至飞速进步(很快就成了洋枪洋炮)，而传统的产品则难以受益于当时的技术进步.
.. 蒸汽船取代大帆船, 更多的是受益于当时工业革命的大环境。当时，以机械发明为代表的工业革命，任何一项技术的进步都可以帮助蒸汽船进步，但是那些技术对改进大帆船的帮助却不大。
.. 谷歌的算法, 本质上是通过连接改进搜索的相关性，而之前的搜索都是从网页本身和关键词的相关性出发。随着互联网越来越大，连接也越来越强，而传统的搜索方法难以受益于这种进步，但是谷歌的算法可以。因此，在谷歌只有十几个人时，几千人的搜索引擎公司就已经竞争不过它了。
.. 微软长期以来基于电脑, 而谷歌基于互联网，任何互联网技术的进步都能非常自然地帮助到谷歌，却对微软帮助不大。


|2. 生产关系不是一个时代的
|- 从生产关系来讲，成功的小公司和现有的大公司不属于同一代。
.. 在拿破仑战争期间，法军在数量上一直处于劣势，但是拿破仑的战术思想却领先欧洲君主整整一个时代，从炮兵、步兵的配合到后勤补给都领先。

|===






---


==== 销售的本质：把钱收回来

- 把东西卖出去, 只完成了销售的一半. 还有另一半，也是最关键的一半，就是“把钱收回来”，否则卖了还不如不卖。把钱收回来是目的，而把货卖出去只是手段.
.. 很多给沃尔玛供货的中国公司，宁可忍受沃尔玛的压价，也愿意和它做生意，因为它们从沃尔玛那“把钱收回来”的成本低。

- 在美国, 拖欠账款和赖账的现象也很明显. 他们的做法就是: **加收很高的利息，同时对"先付账"的予以折扣优惠。**美国人在定价时, 通常会留一个比例，比如 5%作为收款的成本，你如果先付账，可以省去这个成本。


---

==== 商业的本质 : 是让人(消费者)多花钱，而不是省钱 -> 因此好的生意领域, 是能够增加消费者"消费频率"的生意领域.

- 自从工业革命之后, 生产过剩, 全世界经济就进入了要靠消费量, 来拉动"供大于求"的时代.

- *商业的本质 : 是让人(消费者)多花钱，而不是省钱. 因为即使人省了钱、有了时间，最终依然是要花出去的*(羊毛出在猪身上, 让别人赚不如你来赚) (增长黑客).   +
*因此好的生意领域, 是那些能真正提高消费者使用频率的生意领域.* 如果人们对某样事物的需求量不会变大, 那么这个生意市场就不存在做大的可能性(只会同行内零和博弈). 因此很多被炒作的"共享经济", 其实不具有做大蛋糕的增量性.

.. 他太太半个月做一次指甲，并不会因为有了共享平台就天天做指甲(消费频率不会提高)，因此这个生意, 整个行业的市场规模不会扩大, 只会行业内争食.
.. "共享充电宝", 虽然手机充电是刚需，但是充电却不是。消费者不可能因为有了租赁充电宝，就从每天使用手机5小时,变成每天使用10个小时, 即充电频率不会增加.

---

==== 把产品做成牙刷(每天刚需)

刚需, 通过永不停止的频次, 就会令消费者养成使用习惯.

要做到两点:

- 既然每天都要用, 产品功能的"可靠性"和"稳定性"就非常重要. 如果它时灵时不灵，哪怕 99%的时间是好的，1%的时间不能用，大家都会觉得不可靠。

- 需要按固定周期更新(推陈出新)(比如 Apple 每年都会推出新 iphone). 每过一段时间就要给大家带来一个惊喜，提醒它的存在。
.. 如果哪家公司不能够在进入购物季之前推出新产品，那么明年的销售就成问题了.
.. 自媒体, 有时更新，有时没有，大家就会觉得结果不可预期，就不会每天来，每天关注的习惯就养不成。

---

==== 提高消费频率 -> 让顾客把买的东西尽快用光

- 搞会员充值, 但消费者在花光卡里的钱之前, 是没有动力继续充值的，接下来的促销就难以开展。顾客在花完充值的钱以前，商家很难说服他们再次充值。

- 这个思路用在管理中, 你给员工的奖励就不能仅仅是一次充值的促销，然后让他们享受很多年.
.. 在谷歌，一个员工每一次升迁，在得到大笔奖励的同时，之前全部的贡献就会清零；下一次升迁所依据的贡献, 要从前一次升迁后算起，而不是基于历史上全部的贡献。

---

==== 让消费者有面子

*对于社会底层的人，有了面子可以多少增加一点自信心*，让他们能够在工作和生活中表现得更出色些。因此，任何一个好的产品，都需要做到顾及使用者的面子。


---


== 做生意, 管理公司

==== 互联网只是个工具, 核心依然是原有产业

- 原有刚需产业和新的技术, 更多的是合作关系，而不是颠覆关系。 *互联网只是个工具, 核心依然是原有产业*。 在今天的互联网时代，银行业、广告业、零售业本身都没有消失，而是以新的、更有效率的形式存在下去。因此, *原有产业才是每一个创业者应该思考的入手点。*

- 很多做人工智能的小公司在寻求融资时，总说自己的技术比谷歌好、比阿里巴巴新，这种可能性近乎为零. 投资人也不会相信.  +
人工智能技术的发展, 在很大程度上是依靠数据和计算机数量的，没有这个基础，即使最著名的大学也难以在技术上有突破。

---

==== 业务的选择




---

==== 新产品获得市场认可, 必经的三个阶段

[cols="1,2a"]
|===
|阶段 |Header 2

|第一阶段 :  +
虽然有了一个革命性的发明，但是毛病很多，只有极客才会关注和使用它。
| - 创新中的从0到1只是完成了第一步。真正的创新，是要走完从0到N的全过程。
- 硅谷中的很多科技产品, 技术发明, 其实源于麻省理工学院，但是很多原创的发明在那里做出之后, 常常没有了下文。麻省理工学院也没有创立出太多了不起的公司。

|第二阶段:  +
解决了第一阶段大部分问题，但是价格昂贵，因此只有有钱人才会使用。
|

|第三阶段:  +
解决了价格问题，才普及到大众。
|- *科技实际上只是硅谷中这些梦想改变世界的叛逆者们的工具而已。*
- 他们首先会想尽办法去**寻找那些可能颠覆现有产业的技术（注意：是寻找而不是发明)**. 那些在其他地区(比如麻省理工学院)被发明却又被束之高阁的技术，被硅谷的颠覆者带到硅谷, 继续发扬光大。而新技术常常不可靠，要将这样的技术转变成产品，需要克服一个又一个困难，走完从1到N的漫长路程。
|===

绝大部分产品，三个阶段是由不同公司领跑的. 前两个阶段的公司可能在商业上都不成功，甚至倒闭.

---

==== 管理的本质 : 应对波动

- 不管是做投资也好，还是做企业的经营也好，我们核心就是怎么样去应对波动(资产价值的波动, 经济的波动).

- *很多管理者动不动就修改规章制度，世界上没有一种制度是完美的.* “一将无能，累死千军”，伪工作的管理者便是如此。


---

==== 招人

- 公司招人, 要围绕公司的价值观要求, 去招聘最合适的人(他们必须能认同公司的价值观).

- 录用的人, 应该高出现有员工的平均水平，否则公司越大(人员越多)，人员的平均素质就会越被拉低。

---


==== 薪水

- 高盛之所以给他们那么多的奖金，既不更多，也不更少，是由市场决定的。如果高盛每个人出去创业都能成功，高盛就会自动地将分成比例提高。这反过来说明了创业的失败率.

---

==== 升职

- 在美国，大部分人通常一辈子只能被提升两次，在谷歌这样的企业最多也就多一次。
.. 在美国，20%最底层（按照经济收入）的人，只有 4%(也就是绝对人数的 0.8%)的人最终可以进入最上层的行列，这个比例是非常低的。


- 任何想进阶的人都, 不应该被动地工作，就像算盘珠子，拨一拨，动一动。想成为领导者，要平实地学习做一个领导，走出自己的一亩三分地. *我们在任何时候都应该想一想，当我们离开时, 我要给自己带走什么, 及, 我要给这个团队留下什么。*
.. 工程师们的问题在于：一锤在手，满眼都是钉。今天，有点儿工程经验又懂一点统计的软件工程师，常常把什么事情都看成是大数据的问题.
.. 如果一个开发人员不清楚自己所做的产品盈利能力如何，是非常危险的。

- 很多公司在刚成立时由创始人负责，但是成长起来后就交给了职业经理人，然后给创始人一个"总裁"的虚职以表示尊重。 +
今天在美国大部分公司里，"首席执行官"是实职，"总裁"反而是虚职，有点儿荣誉职位的意思。







---


== 人生观

==== 目的和手段

做销售, 把钱收回来是目的，而把货卖出去只是手段. 在生活中, 希望我放弃休息或者和为家人安排好的休假，来参加什么重要活动，那是万万没有可能性的，因为**我不会把目的和手段颠倒过来。**

---

==== 和人相处的技巧 : 让对方感觉对你有所需求

- 世界上所有的人都喜欢自己来买东西，而不是被人推销来买东西，因此那种求人的营销一定无法成功。
.. 我经常看到一个男生为了追求一个女生，绞尽脑汁、极尽努力地去讨好对方、迁就对方，对方就是爱搭不理。这对被追求的女生而言，其实就是一种被强制推销的感觉。

---

==== 沟通

- *最有效的沟通是在第一时间直接给出答案，然后补充解释。而不要说没有信息量的废话!*

.. *事实上我问这个问题时并不关心准确的细节，只想了解一个大致范围而已。他可以直接回答一个动态范围.* 因此，如果他简单地回答17%左右，也是一个不错的答案。如果这位工程师无法给出整体的回答，他至少也应该给出自己所说的每一种具体情况下的具体答案，而不是讲了一堆废话。最有效的沟通是在第一时间直接给出答案，然后补充解释。

.. 我曾经问过爱奇艺创始人龚宇一个类似的问题，让他就某一位网红的一期视频节目的收入做一个估算，*虽然这里面有好多变数我们不知道，他也没有见过那位网红，但是他能马上告诉我一个比较准确的范围*，这样大家就能知道一件事情是不是值得在爱奇艺或者类似的网站上做。这就是管理者和被管理者在掌握大局上的区别。 +
善于沟通的人会理解对方提问的目的，然后提供有用的信息，而不是按照自己的意思解释字面上的问题。

....
.. 我问过某公司里一位资深律师这样的问题：“最近在国内，专利从申请到批准的周期是多长？”她的回答是：“我们主要负责专利的书写和申请，审批的速度不很清楚，这要看情况，有的很快就批准了，有的要修改补充材料，个别的拖了很长时间。”
**这个回答的问题在哪里呢？它是没有信息量的废话！我当然知道**专利律师是书写和申请专利的，不是专利局的审批人员；也知道不同专利被批准的时间不一样长。 +
我又接着启发她，问道：“大约有多少比例的专利能在两年内被批准？平均是多长时间？最长的是多长时间，那些情况是否是个案？”
我得到的回答是这样的：“不知道，我只负责一部分专利的申请，这些数据可能要找专利局的人去了解。” +
我当然知道专利局会有统计数据，但是作为一个在行业里工作多年的律师，对这种基本数据是应该了解的。 +
我顺着她的话追问：“不用管专利局那边的数据，就你的公司过去的经验，哪怕是那些你负责的案子，总体情况是怎样的呢？”这位律师颇有歉意地对我讲：“哎呀，我还真没统计过。” +
我还接触过不少其他从事具体工作的专业人士, 很多表现也是如此。我想，如果你是一个老板，也未必会提拔这样的人当领导，负责起一个部门。
....





---

==== 通识教育

- 人有两个上帝赋予的特殊天赋, 是机器无法取代的：
1. 艺术的创造力和想象力
2. 梦想, 和浪漫的情怀

-















