
= 问题_利润最大的环节在哪里
:toc:

---

== 做任何事时, 付出任何代价时, 你都要问自己 : 你颠倒了"目的"和"手段"吗?

在生活中, 希望我放弃休息或者和为家人安排好的休假，来参加什么重要活动，那是万万没有可能性的，因为**我不会把目的和手段颠倒过来。**

*今天科技进步的结果，应该是让更多的人能够过上优雅而从容的生活，而不是让大家变得没有时间生活*，这就是我对技术进步的期望。*幸福生活才是根本，其他都不过是达成这个目的的手段而已。*


---

== 捡西瓜还是捡芝麻? -> 捡芝麻捡得再勤劳，也捡不出西瓜的重量。

郭台铭是捡西瓜，王妈妈则是捡芝麻。一个西瓜的重量是芝麻的两万多倍，因此，*捡芝麻捡得再勤劳，也捡不出西瓜的重量。*

很多产品在线服务的流量和盈利能力非常有限，贡献的都是一些小芝麻，把它们最后加起来，还不如谷歌一个产品带来的收入高。


看看下面这些在生活中捡芝麻的行为:

- 为了省一元出租车钱，在路上多走 10 分钟。
- 为了抢几元钱的红包，每隔三五分钟就看看微信。
- 为了挣几百元的外快，上班儉偷干私活。
- 为了“双十一”抢货不睡觉。
- 为了一点折扣在网上泡两个小时，或者在北京跑五家店。
- 为了拿免费的东西打破头。


通常，人的晋级上一个台阶，贡献、职责、影响力就可能增加一个数量级，至于收入就更不用发愁了。当然，*世界上捡芝麻的人多、捡西瓜的人少*. 大部分人捡芝麻的思维方式一辈子也改不了，*也正是因为这样，才给那些立志于捡西瓜的人足够的机会*，西瓜自然就留给了你这样有智慧的人。

有人说，我没有遇到西瓜啊，其实不是没有遇到，而是**因为你满眼都是芝麻，天天为捡芝麻而忙碌，就没有机会练就捡西瓜的能力了。**




---

== 在消费链条中哪一环是绕不过去的, 那一环就能挣到最大的钱.

---

== 好的生意领域, 是能够增加消费者"消费频率"的生意领域.

商业的本质 : 是让人(消费者)多花钱，而不是省钱. 因为即使人省了钱、有了时间，最终依然是要花出去的. 让别人赚不如你自己来赚.

*因此好的生意领域, 是那些能真正提高消费者使用频率的生意领域. 如果人们对某样事物的需求量不会变大, 那么这个生意市场就不存在做大的可能性(只会同行内零和博弈).*
因此很多被炒作的"共享经济", 其实不具有做大蛋糕的"增量性"存在.

- 他太太半个月做一次指甲，并不会因为有了共享平台就天天做指甲(消费频率不会提高)，因此这个生意, 整个行业的市场规模不会扩大, 只会行业内争食.

-  "共享充电宝", 虽然手机充电是刚需，但是充电却不是。消费者不可能因为有了租赁充电宝，就从每天使用手机5小时,变成每天使用10个小时, 即充电频率不会增加.

---




