
= 问题_(影响力)_如何引导他人干你想让他们干的事
:toc:

---

== 收益函数 <- 员工会不自觉地朝着收益最大化的方向努力

- 如果一个公司认定技术最重要，产品的稳定性最重要，那么久而久之，"工程师"就成了这个公司中最有权势的群体，那么工程师文化就成为公司的显性基因。谷歌就是这样的公司。

- 如果一个公司认定技术不是最重要的，用户体验最重要，那么在这样的公司里"产品经理"就是最有拍板权势的，工程师只好围着产品经理转. 苹果、Facebook和腾讯就是这样的公司。

- 如果一个创始人只看重销售业绩，一切以商业为先，那么这样的公司就是一个"销售导向"和"结果导向"的公司，无论是产品经理还是工程师，都要围绕着销售目标转，阿里巴巴就是这样的公司。

---

== 将行动的理由, 归因于是对方的内在原因, 而非外在原因

....
社会心理学实验, 问: “为什么你要和你的女/男朋友出去约会？”.
内在的原因, 如, 因为我们拥有共同的兴趣和关注点.
外在原因 : 如, 因为他／她认识很多重要人物.
....

结果发现，那些注意力被引到外在原因方面的人，比那些关注了内在原因的人，对他们的恋人表示出较少的爱恋，认为结婚的可能性也较小。

---

== 用"坏事"促进人 -> 坏事总是比好事更有影响力，而且影响更持久

- 一件坏事（创伤）比一件好事能产生更为持久的效应。
- 坏事变坏要, 比好事变好, 对我们产生更大的影响。
- *破坏性行为对亲密关系的伤害程度，要比建设性行为的促进作用更大。*
- 一个不好的名声比起一个好名声更容易获得，而且更难以摆脱。 （仅仅一次说谎就可以毁掉一个人“诚实”的美誉）

- 日常生活中发生的坏事，比好事更能引起人们的注意和思考。(死亡比出生更能引起人们对生命意义的探寻。)

- 坏心情比好心情, 更能影响我们的思维和记忆。


---

== 锚定 -> 第一个锚（往往是任意决定的）不仅影响我们当时的购买决定，而且影响后来的许多决定。

早在19世纪，心理物理学家就发现，*人们对相对差异非常敏感，对绝对数值则不怎么敏感。*

- 写下社会保险号后两位数影响了他们的最后出价，学生中社会保险号后两位最大的（从80到99）出价最高，那些后两位最小的（1到20）出价也最低。

同时, *一旦参与者愿意出某价买某物，他们此后购买同类产品也会参照他第一次的出价（锚）来决定的出价意愿。* 首次的价格大都是“任意”的，并可能受到任意问题答案(即"锚")的影响；可是一旦这些价格在我们大脑中得到确立，它形成的便不仅是我们对某一产品的出价意愿，还影响了我们对其他有关产品的出价意愿（这使它们一致）。

不过价格标签本身并不是锚。它们是在我们深入考虑后，想用某一特定价格购买某一产品或服务时才会成为锚。从此以后，我们愿意接受的一系列价格——就像蹦级绳的拉力，总是需要参照原先的锚来决定。因此，*第一个锚不仅影响我们当时的购买决定，而且影响后来的许多决定。*

- 搬家到另一城市的人购房时, 总是被原住城市的房价所锚定。(宾夕法尼亚大学经济学家尤里•西蒙森和卡内基•梅隆大学教授乔治•勒文斯坦发现)






---

[cols = "1,2a"]
|===
|Header 1 |Header 2

|Column 1, row 1
|Column 2, row 1

|Column 1, row 2
|Column 2, row 2
|===


























