
= 话语输出影响力
:toc:

---

== 如何对应你不太熟悉的提问? -> 无法给出精确的数据答案, 就给出"值"的预估范围

- 最有价值含量的沟通, 是在第一时间直接给出答案，然后补充解释。而不要说没有信息量的废话!


|===
|我问 |他回答 | 他的问题点

|我问一位资深律师: “最近在国内，专利从申请到批准的周期是多长？
|“我们主要负责专利的书写和申请，审批的速度不很清楚，这要看情况，有的很快就批准了，有的要修改补充材料，个别的拖了很长时间。”
|**这个回答的问题在哪里呢？它是没有信息量的废话！我当然知道**专利律师是书写和申请专利的，不是专利局的审批人员；也知道不同专利被批准的时间不一样长。

|“大约有多少比例的专利能在两年内被批准？平均是多长时间？最长的是多长时间，那些情况是否是个案？”
|“不知道，我只负责一部分专利的申请，这些数据可能要找专利局的人去了解。”
|我当然知道专利局会有统计数据. 但是作为一个在行业里工作多年的律师，对这种基本数据是应该了解的。

|“不用管专利局那边的数据，就你的公司过去的经验，哪怕是那些你负责的案子，总体情况是怎样的呢？”这位律师颇有歉意地对我讲：“哎呀，我还真没统计过。”
|
|如果你是一个老板，也未必会提拔这样的人当领导，负责起一个部门。

|===

- *事实上我问这个问题时并不关心准确的细节，只想了解一个大致范围而已。他可以直接回答一个动态范围.*

- 我曾经问过爱奇艺创始人龚宇一个类似的问题，让他就某一位网红的一期视频节目的收入做一个估算，*虽然这里面有好多变数我们不知道，他也没有见过那位网红，但是他能马上告诉我一个比较准确的范围*，这样大家就能知道一件事情是不是值得在爱奇艺或者类似的网站上做。这就是管理者和被管理者在掌握大局上的区别。

- 如果这位工程师无法给出整体的回答，他至少也应该给出自己所说的每一种具体情况下的具体答案，而不是讲了一堆废话。

---

== 如何将事情讲得非常清楚?

==== 演讲要点一般不要超过三条 -> 超过三条大家根本记不住

- 很多人演讲时，恨不能把一肚子话一口气倒给听众。其实**大部分人在听报告时，都很难集中注意力超过20 分钟。** +
因此，*再好的演说家都很难把 10 件事一次性讲清楚，能把一件事讲透或者三五个要点提到，目的就达到了。*
+
如果听众真有兴趣，他们以后还会来听的，到那时再把更多的信息传递给他们也不迟。 +
如果听众没有兴趣，即使讲再多的内容，也会成为最后一次演讲。


- 对于任何演讲者，都**不要指望一次演讲能够讲清楚 10 件事，真能把一件事讲清楚，目的就达到了。**

- 把报告做得简短点，重点突出即可。听众能够专心听 5 分钟，记得里面一两个重要的观点，报告的目的就完全达到了。

- 我做报告时，演讲要点一般不会超过三条，超过三条大家根本记不住。


---

==== 你的每段话, 都要有其目的


我代表基金做了一个简短的讲话。一般来讲,参加基金年会的人数并不多，主要是我们现有的投资人、未来潜在的投资人, 以及我们所投资公司的创始人三类。 +
我一共只有 5 张 PPT，每张 PPT 用两分钟时间讲完，大致讲了 5 个方面的内容。

[cols="1,3a"]
|===
|Header 1 |Header 2

|第一张 PPT： +
*我们是谁，过去几年做了什么事情*
|这张 PPT 的**目的既是对过去的一个总结，和对现有的投资人一个交代，也是为了吸引新的投资人给基金投资。** +
在这张 PPT"里，我介绍了几个数据：

1. 我们过去投了多少家公司。
2. 目前所投资公司的估值增长了多少。
3. 有多少公司成功退出了(钱收回来了)。
4. 有多少公司失败了。（这一条一定不要省略，无论是投资人还是办企业的人都是聪明人，任何报喜不报忧的行为只能让他们心存疑虑。 +
很多时候，*先把坏消息告诉大家，然后再说好消息，效果会更好*。如果坏消息不是很坏，说出来反而能起到好的作用。）

这张 PPT 要传递的第二个信息, 就是用一句话概括“我们”的特点，即我们对技术的高度敏感性。很多时候，话说多了反而没有重点，把上面这几点意思表达到位就非常好了。

|第二张 PPT： +
*我们提供什么*
|即使是钱，也分聪明钱和傻钱。*对于创业者，除了钱，我们还提供两方面的帮助。*

1. 第一，提供一种连接。我们首先会为创业公司提供和硅谷企业, 以及硅谷其他投资机构, 的连接服务。其次，对于那些想进入中国市场的公司，我们会提供解决方案。
2. 第二，对创业者提供一种"技术上"和"管理上"的帮助。因为我们的合伙人都是技术专家出身.

|第三张 PPT： +
*我们投资的哲学*
|看重创始人，也就是“投人”。我还展开讲了“投人”的三点重要性：

1. 一流的人可以把二流的项目做成一流；反之，二流的人会把一流的项目做成二流或三流。
2. 世界是瞬息万变的，任何成功的初创企业最终的成功产品，相比当初创始人的想法都会有很大变化。世界需要“变色龙”，只有一流的人才善于往好的方向改变。
3. 人的诚信很重要。

在风险投资领域有一条金科玉律——*投资就是投人。诚信比能力更重要*。 +
在风险投资中，当你把几百万元、几千万元，甚至更多的钱，在没有任何抵押的情况下交给一个不认识的人，让他创业，这个人首先必须让你信得过。创业者如果骗投资人的钱，通常投资人是毫无办法的。

我见过不少创业者，一旦办公司办得不顺，就把公司的技术和产品拿出去再办一个公司，去融新的资金。同时他们会对原来的公司进行破产清盘，这样投资人的钱就不用还了。

国内一个非常有名的早期投资人，或许是被这种没有诚信的创业者坑苦了，在后来给创业者投钱时都要加上一个霸王条款一如果你拿了我的钱把公司办砸了，只要你还打算继续办公司，我给你的投资永远算到你的新公司里。


|第四张 PPT： +
*我们对项目的看法*
|我帮你解决了钱的问题之后，*你只要告诉我，当你实现了自己的想法后，世界会有什么明显的、正面的变化。*

对于那些做所谓“me too”（我也能行）项目的人，这一条就通不过，因为他们即使达成了目标，也只不过使行业中多了一个竞争对手，对世界没有什么帮助。

出于对这个原则的坚守，我们几乎不投资那些炒作概念的公司，那些最终把公司做得很大的人，都是有明确愿景和方向的，不是随大溜去盲从、去热炒概念，也不会挤进过热的市场。 +
前几年那些大量做视频的公司、团购的公司、O2O 的公司，以及现在的大部分自媒体，都不符合我们这个要求。

|第五张 PPT： +
*我们对所谓"趋势"的看法*
|所有 IT 行业的人都习惯于把“趋势”二字挂在嘴边，有些人还在大会小会上到处预测趋势。当然，几年后你回过头来验证他们所说的话，常常是不准确的。

**预测常常是靠不住的，因此，我们在投资时从来不去赌未来的趋势。什么方向的公司可以投资，什么领域里的公司不可以，完全是创业者告诉我们的。**

如果很多人几乎同时看到了类似的问题、有相似的想法，这就是所谓的趋势。这种趋势，不是哪个专家先知先觉的结果，而是自下而上总结出来的。

好的体制要让动力来自底层，刹车掌握在高层手里。对于创新也是如此，动力应该来自底层的每一个创业者，而制动应来自掌握资金和资源的人。因此，*风险投资所做的事情，就是对创业者的想法进行正确的判断。对于趋势，我们从不预测，但是我们会知道趋势所在，因为创业者会告诉我们。*
|===

在战术层面，我的**后四张 PPT 都是在支持第一张 PPT 的内容**，这样**整个 10 分钟的报告就传递出一个统一的信息 -- 我们为什么过去做得不错，以后为什么有信心能够做得更好。**这样既能让现有投资人放心，也要让未来投资人动心。

---



















