
= 问题_(自身_能力&魅力)
:toc:

---

== 人生观

==== 生死观

- *人一出生，死期已定. “这个世界大家其实都在排着队沿着一条路往前走，停不下来，走到尽头就是死亡。这时，有些男人和女人搭上了腔，开始说笑起来，更多的人参与了进来，整个队伍便充满了欢乐。”我想，我们的生活其实就应该是这样的。*

- *所有传世的文学作品，无论呈现的现实多严酷，都有一股借着"肯定生命"来对抗"生命无常"的基本反抗精神。*

---

==== 不要有玻璃心 -> 金字塔结构永远存在底层, 没什么大不了的. 想想刘玄德

清华大学入学时，一个年级 200 多名新生都是原来学校最顶尖的学生，但到了第一学期的期中考试，总要有最后一名，总要有最后 1/3 的学生，这时候哪些人是玻璃心马上就看出来了。


---

== 见识的来源与高度

==== 圈子的重要性在哪里? -> 人脉更是需要从一个好的同学圈子获得，这样将来他们可以互相提携.

哈佛商学院教给大家的第一个思想精髓是学会“玩儿”，即营造你的同学圈子。哈佛商学院要培养的是精英. **精英和普通人的差别不完全在于知识的多少，而在于1.智慧和2.人脉。1."智慧"需要和大师、和高水平的人在一起切磋才能获得；2."人脉"更是需要从一个好的同学圈子获得，这样将来他们可以互相提携。**因此，来上课(与同学接触交流)是成为精英的必由之路；至于考试，反而在其次。

- 学院里每一个学生多少都得有点儿特长，这些是面试时考查的一方面，否则无法和大家玩儿到一起去，以后最好从小培养孩子的特长，否则长大了就难以挤进那个圈子。*如果在哈佛商学院不会玩儿，恐怕 2/3 的学费是白交了.*

- 在耶鲁大学，学生一半的时间都花在了课外活动中，**因为这些看似和考试无关的活动，培养了学生的各种优秀品质，比如拼搏精神、团队精神、领导能力、社交能力、表达能力、全球视野和社会责任感。**事实上，如果在哈佛和耶鲁没有学到这些内容，就失去了在那里读书的意义。

-  “玩儿”的活动多一晚上经常有晚会，周末有各种活动。**参加这些活动的，不仅有学生们自己，而且有很多来自硅谷大公司里的资深人士和高管。**12 个月这么玩儿下来，除非特别不合群的人，否则想不融入一些圈子都难。今天中国的长江商学院等著名商学院，也非常看重一同参与学习以外的各种活动.

- *只有在最好的大学里，才有最好的海外交换学习的机会. 更重要的是，它们有最强的同学圈子，甚至找到好伴侣的机会更大。*


---


==== 没有见识，视野就被局限了 -> 想用短期的方法达到长期的目标，这是不可能的

- 商鞅游说秦孝公一共进行了三次，第一次商鞅讲尧舜禹汤的大道，秦孝公听得睡着了。第二次见面讲（周）文王、武王的王道，秦孝公听的有了点儿兴趣. 第三次，商鞅以霸道(春秋五霸)说孝公，孝公听得津津有味. +
那为什么商鞅不一开始就谈富国强兵，称霸诸侯，而前两次先谈帝道、王道？商鞅说：“我是怕如果他真是一个有大志向的人，我一开始就说那些低层面的事情，把他看低了。但既然他只对霸道感兴趣, 这样一来（急功近利)，国运终究不可能超过商朝和周朝。”
+
*秦孝公想用短期的方法达到长期的目标，这是不可能的。生活中很多人也同样问我一些如何用短期的方法达成长期的目标的问题，比如学什么专业可以挣大钱、如何快速获得成功等，我也很难回答。*

- 后人评析: 商鞅的变法, 失败原因:  重"术"(只有短期激励效果)(军事政治上), 而缺乏能带来长期效果的在"教育"(改造人民头脑)和"文化"(改造人民习惯习俗)上的变革, 这也导致秦国世风颓坏. *这也与当时改革领袖理论的贫乏, 有很深的关系.* +
(秦惠文王做太子时, 因犯法而累受商鞅处罚. 他即位后, 进行报仇, 诬告商鞅谋反. 商鞅逃回自己封地商县, 起兵抗秦, 兵败被杀.)

- 几位领导干部询问我对亚投行的建议，我反问道，如果明天就必须在世界 20 个国家开设办事处(或分行)，如果再加上四大国有银行, 将来要进入世界主要国家，谁来当分行行长？因此，我说要尽快培养具有国际金融能力的领袖。

- 企业家的子女, 挑选专业, 所需要的是能学习到大视野, 以将来接班，而不是会计这样一个具体的技术。会计这种人，在社会上可以花钱请到.


---

== 必须要有表示友善和爱的能力 -> 缺乏爱的人难以大气，不大气的人做不成大事.

比友善更进一步的是爱，既包括爱情，也包括爱慕、慈爱或者欣赏。不论哪一种，人都需要懂得如何表达。如果一个人想在社会阶层上再往上跃迁几个台阶， 这个能力(表示友善和爱的能力)是必须要学会的。

不懂得关爱别人、不懂得分享, 没有培养关爱他人的习惯，以至他们长大以后非常小家子气。缺乏爱的人难以大气，不大气的人做不成大事。


---


== 社会活动时的体面

他们从小要学习如何参加社会活动，学习贵族礼仪。但是，贵族在举止上最重要的, 是在自然危险面前的淡定。用中国话讲，就是“泰山崩于前而色不变”。

- 美国军人在下雨时是不打伞的，更不会匆忙奔跑避雨，他们正确的举止是穿着雨衣在雨中列队快速行走。为什么要这样？因为一名军人在灾害面前必须沉稳。
- 奥巴马出席户外新闻发布会，下起了雨，奥巴马随即让身边的海军陆战队士兵帮忙撑伞挡雨，结果招来批评。重要的原因在于作为总统, 这种行为有失体统,  缺了点贵族气概。

---



