
= 问题_小公司在行业巨头下的生存空间窗口有多久
:toc:

---

== 大公司不愿干的脏活累活, 就是小公司的生存空间领域(暂时)

以AI人工智能为例. 有三种公司能够受益于"人工智能"技术:

==== 1. 技术领先的大公司 (谷歌、亚马逊、微软、阿里巴巴等) -> 自己干AI

==== 2. 具有大量数据的传统公司(电信运营商、银行，地方政府) -> 信不过IT巨头, 会把核心业务

传统公司中, 那些商业规模非常大, 但商业模式老旧. 拥有大量数据, 但是在数据变现之前, 它们并不等于钱. 这些公司难以依靠自己的力量从大数据中挖掘金矿。

这第二类公司是不会将自己的核心业务, 委托给第一类公司的。因为存在利益冲突, 或者潜在的利益冲突. 可以想象，四大国有银行信不过阿里巴巴; 中国移动信不过腾讯.

反之，第一类公司也不愿意去做那些脏活、累活，而且一开始是低利润的工作。因为从成本上来讲不合算。

这就给了小AI公司机会。 (巨头吃肉, 小创业公司吃巨头挑剩下的渣)

(但是外包给乙方的甲方核心技术, 终究会被甲方收回. 甲方现在只不过是暂时借助乙方的力量, 来帮助甲方发展起技术水平而已. 正如中国接了世界外包的活, 但最终一定会自己"产业升级".)


很多做人工智能的小公司在寻求融资时，总说自己的技术比谷歌好、比阿里巴巴新，这种可能性近乎为零. 投资人也不会相信.  +
人工智能技术的发展, 在很大程度上是依靠数据和计算机数量的，没有这个基础，即使最著名的大学也难以在技术上有突破。

原有刚需产业和新的技术, 更多的是合作关系，而不是颠覆关系。 *互联网只是个工具, 核心依然是原有产业*。 在今天的互联网时代，银行业、广告业、零售业本身都没有消失，而是以新的、更有效率的形式存在下去。因此, *原有产业才是每一个创业者应该思考的入手点。*




---

== 具有哪些特点的小公司, 能够逆袭大公司?

==== 1. 技术不是一个时代的

*同时代的其他技术进步, 能更多促进自己的技术发展, 而非更多促进别人的.*

颠覆者（小蚂蚁）的创新, 一开始一定有很多不完善的地方, 但它必须容易得到当时相关技术的帮助，以至飞速进步(很快就成了洋枪洋炮)，而传统的产品则难以受益于当时的技术进步.

- 蒸汽船取代大帆船, 更多的是受益于当时工业革命的大环境。当时，以机械发明为代表的工业革命，任何一项技术的进步都可以帮助蒸汽船进步，但是那些技术对改进大帆船的帮助却不大。
- 谷歌的算法, 本质上是通过连接改进搜索的相关性，而之前的搜索都是从网页本身和关键词的相关性出发。随着互联网越来越大，连接也越来越强，而传统的搜索方法难以受益于这种进步，但是谷歌的算法可以。因此，在谷歌只有十几个人时，几千人的搜索引擎公司就已经竞争不过它了。
- 微软长期以来基于电脑, 而谷歌基于互联网，任何互联网技术的进步都能非常自然地帮助到谷歌，却对微软帮助不大。

---

==== 2. 生产关系不是一个时代的

- 在拿破仑战争期间，法军在数量上一直处于劣势，但是拿破仑的战术思想却领先欧洲君主整整一个时代，从炮兵、步兵的配合到后勤补给都领先。

---


























